-- TASK 1: property_h_sql.sql

-- Najde změněné záznamy - porovná dnešní data s včerejšími
-- Vloží nové verze záznamů, které se změnily
-- Označí je jako aktuální (`current_flag = TRUE`)


MERGE INTO realitky.cleaned.property_h AS trg
USING (
    SELECT *
    FROM realitky.cleaned.property src
    WHERE src.upd_dt::date = :load_date
    AND (:src_web_filter IS NULL OR :src_web_filter = '' OR src.src_web = :src_web_filter)
    
    EXCEPT
    
    SELECT 
        property_id, 
        property_name,
        address_street, 
        address_house_number,
        ruian_code, 
        address_city, 
        address_state, 
        address_postal_code,
        address_district_code, 
        address_latitude, 
        address_longitude,
        property_type_id, 
        property_subtype_id, 
        property_number_of_floors,
        property_floor_number,
        property_location_id, 
        property_construction_type_id,
        area_total_sqm,
        area_land_sqm, 
        number_of_rooms, 
        construction_year,
        last_reconstruction_year,
        energy_class_penb, 
        property_condition,
        property_parking_id,
        property_heating_id, 
        property_electricity_id,
        property_accessibility_id,
        property_balcony, 
        property_terrace,
        property_cellar,
        property_elevator, 
        property_canalization,
        property_water_supply_id,
        property_air_conditioning, 
        property_gas_id,
        property_internet,
        furnishing_level, 
        ownership_type, 
        is_active_listing,
        source_url,
        description, 
        src_web, 
        ins_dt, 
        ins_process_id,
        upd_dt,
        upd_process_id, 
        del_flag
    FROM realitky.cleaned.property_h hist
    WHERE hist.current_flag = TRUE
    AND (:src_web_filter IS NULL OR :src_web_filter = '' OR hist.src_web = :src_web_filter)
) AS src
ON (
    trg.current_flag = TRUE
    AND trg.valid_from = :load_date
    AND trg.property_id = src.property_id
    AND trg.src_web = src.src_web
)
WHEN MATCHED THEN UPDATE SET
    trg.property_name = src.property_name,
    trg.address_street = src.address_street,
    trg.address_house_number = src.address_house_number,
    trg.ruian_code = src.ruian_code,
    trg.address_city = src.address_city,
    trg.address_state = src.address_state,
    trg.address_postal_code = src.address_postal_code,
    trg.address_district_code = src.address_district_code,
    trg.address_latitude = src.address_latitude,
    trg.address_longitude = src.address_longitude,
    trg.property_type_id = src.property_type_id,
    trg.property_subtype_id = src.property_subtype_id,
    trg.property_number_of_floors = src.property_number_of_floors,
    trg.property_floor_number = src.property_floor_number,
    trg.property_location_id = src.property_location_id,
    trg.property_construction_type_id = src.property_construction_type_id,
    trg.area_total_sqm = src.area_total_sqm,
    trg.area_land_sqm = src.area_land_sqm,
    trg.number_of_rooms = src.number_of_rooms,
    trg.construction_year = src.construction_year,
    trg.last_reconstruction_year = src.last_reconstruction_year,
    trg.energy_class_penb = src.energy_class_penb,
    trg.property_condition = src.property_condition,
    trg.property_parking_id = src.property_parking_id,
    trg.property_heating_id = src.property_heating_id,
    trg.property_electricity_id = src.property_electricity_id,
    trg.property_accessibility_id = src.property_accessibility_id,
    trg.property_balcony = src.property_balcony,
    trg.property_terrace = src.property_terrace,
    trg.property_cellar = src.property_cellar,
    trg.property_elevator = src.property_elevator,
    trg.property_canalization = src.property_canalization,
    trg.property_water_supply_id = src.property_water_supply_id,
    trg.property_air_conditioning = src.property_air_conditioning,
    trg.property_gas_id = src.property_gas_id,
    trg.property_internet = src.property_internet,
    trg.furnishing_level = src.furnishing_level,
    trg.ownership_type = src.ownership_type,
    trg.is_active_listing = src.is_active_listing,
    trg.source_url = src.source_url,
    trg.description = src.description,
    trg.del_flag = src.del_flag,
    trg.upd_dt = current_timestamp(),
    trg.upd_process_id = :process_id
WHEN NOT MATCHED THEN INSERT (
    property_id, 
    property_name, 
    address_street,
    address_house_number,
    ruian_code, 
    address_city, 
    address_state,
    address_postal_code,
    address_district_code, 
    address_latitude, 
    address_longitude,
    property_type_id, 
    property_subtype_id, 
    property_number_of_floors,
    property_floor_number, 
    property_location_id, 
    property_construction_type_id,
    area_total_sqm, 
    area_land_sqm, 
    number_of_rooms, 
    construction_year,
    last_reconstruction_year, 
    energy_class_penb, 
    property_condition,
    property_parking_id, 
    property_heating_id, 
    property_electricity_id,
    property_accessibility_id, 
    property_balcony, 
    property_terrace,
    property_cellar, 
    property_elevator, 
    property_canalization,
    property_water_supply_id, 
    property_air_conditioning, 
    property_gas_id,
    property_internet, 
    furnishing_level, 
    ownership_type, 
    is_active_listing,
    source_url, 
    description, 
    src_web, 
    del_flag,
    ins_dt, 
    ins_process_id, 
    upd_dt, 
    upd_process_id,
    valid_from, 
    valid_to, 
    current_flag
) VALUES (
    src.property_id, 
    src.property_name, 
    src.address_street, 
    src.address_house_number,
    src.ruian_code, 
    src.address_city, 
    src.address_state, 
    src.address_postal_code,
    src.address_district_code, 
    src.address_latitude, 
    src.address_longitude,
    src.property_type_id, 
    src.property_subtype_id, 
    src.property_number_of_floors,
    src.property_floor_number, 
    src.property_location_id, 
    src.property_construction_type_id,
    src.area_total_sqm, 
    src.area_land_sqm, 
    src.number_of_rooms, 
    src.construction_year,
    src.last_reconstruction_year, 
    src.energy_class_penb, 
    src.property_condition,
    src.property_parking_id, 
    src.property_heating_id, 
    src.property_electricity_id,
    src.property_accessibility_id, 
    src.property_balcony, 
    src.property_terrace,
    src.property_cellar, 
    src.property_elevator, 
    src.property_canalization,
    src.property_water_supply_id, 
    src.property_air_conditioning, 
    src.property_gas_id,
    src.property_internet, 
    src.furnishing_level, 
    src.ownership_type, 
    src.is_active_listing,
    src.source_url, 
    src.description, 
    src.src_web, 
    src.del_flag,
    src.ins_dt, 
    src.ins_process_id, 
    current_timestamp(), 
    :process_id,
    :load_date, 
    NULL, 
    TRUE
);