--Model       : ACCOUNTING
--Target table: acc_cinnost
--Mapping     : l1_acc_cinnost
--Style       : Merge
--Purpose     : 
--History:
--Date        Author                    Comment
--10.10.2024   Lukáš Hanzlík             Novy mapping
MERGE INTO l1.acc_cinnost AS target USING (
    SELECT
        property_id,
        property_name,
        address_street,
        ruian_code,
        address_city,
        address_state,
        address_postal_code,
        address_district_code,
        address_latitude,
        address_longitude,
        property_type_id,
        property_subtype_id,
        property_number_of_floors,
        property_floor_number,
        property_location,
        property_construction_type,
        area_total_sqm,
        area_land_sqm,
        number_of_rooms,
        construction_year,
        last_reconstruction_year,
        energy_class_penb,
        property_condition,
        property_parking,
        property_heating,
        property_electricity,
        property_accessibility_id,
        property_balcony_sqm,
        property_terrace_sqm,
        property_garden_sqm,
        property_cellar_sqm,
        property_elevator,
        property_canalization,
        property_water_supply,
        property_air_conditioning,
        property_gas,
        property_internet,
        furnishing_level,
        ownership_type,
        is_active_listing,
        source_url,
        description,
        ins_dt,
        upd_dt,
        del_flag
    FROM
        (
            SELECT
                DISTINCT remax.id, AS property_id,
                remax.property_name AS property_name,
                AS address_street,
                AS ruian_code,
                AS address_city,
                AS address_state,
                AS address_postal_code,
                AS address_district_code,
                AS address_latitude,
                AS address_longitude,
                AS property_type_id,
                AS property_subtype_id,
                AS property_number_of_floors,
                AS property_floor_number,
                AS property_location,
                AS property_construction_type,
                AS area_total_sqm,
                AS area_land_sqm,
                AS number_of_rooms,
                AS construction_year,
                AS last_reconstruction_year,
                AS energy_class_penb,
                AS property_condition,
                AS property_parking,
                AS property_heating,
                AS property_electricity,
                AS property_accessibility_id,
                AS property_balcony_sqm,
                AS property_terrace_sqm,
                AS property_garden_sqm,
                AS property_cellar_sqm,
                AS property_elevator,
                AS property_canalization,
                AS property_water_supply,
                AS property_air_conditioning,
                AS property_gas,
                AS property_internet,
                AS furnishing_level,
                AS ownership_type,
                AS is_active_listing,
                AS source_url,
                AS description,
                CURRENT_TIMESTAMP AS ins_dt,
                CURRENT_TIMESTAMP AS upd_dt,
                false AS del_flag
            FROM
                l0.z013_pohoda_sk_cinnosti
            WHERE
                z013_pohoda_sk_cinnosti.skratka IS NOT NULL
        )
) AS source ON target.property_id = source.property_id
AND target.source_url = source.source_url
WHEN MATCHED
AND (
    target.cinnost_name <> source.cinnost_name
    OR target.cinnost_category <> source.cinnost_category
) THEN
UPDATE
SET
    property_name = source.property_name,
    address_street = source.address_street,
    ruian_code = source.ruian_code,
    address_city = source.address_city,
    address_state = source.address_state,
    address_postal_code = source.address_postal_code,
    address_district_code = source.address_district_code,
    address_latitude = source.address_latitude,
    address_longitude = source.address_longitude,
    property_type_id = source.property_type_id,
    property_subtype_id = source.property_subtype_id,
    property_number_of_floors = source.property_number_of_floors,
    property_floor_number = source.property_floor_number,
    property_location = source.property_location,
    property_construction_type = source.property_construction_type,
    area_total_sqm = source.area_total_sqm,
    area_land_sqm = source.area_land_sqm,
    number_of_rooms = source.number_of_rooms,
    construction_year = source.construction_year,
    last_reconstruction_year = source.last_reconstruction_year,
    energy_class_penb = source.energy_class_penb,
    property_condition = source.property_condition,
    property_parking = source.property_parking,
    property_heating = source.property_heating,
    property_electricity = source.property_electricity,
    property_accessibility_id = source.property_accessibility_id,
    property_balcony_sqm = source.property_balcony_sqm,
    property_terrace_sqm = source.property_terrace_sqm,
    property_garden_sqm = source.property_garden_sqm,
    property_cellar_sqm = source.property_cellar_sqm,
    property_elevator = source.property_elevator,
    property_canalization = source.property_canalization,
    property_water_supply = source.property_water_supply,
    property_air_conditioning = source.property_air_conditioning,
    property_gas = source.property_gas,
    property_internet = source.property_internet,
    furnishing_level = source.furnishing_level,
    ownership_type = source.ownership_type,
    is_active_listing = source.is_active_listing,
    description = source.description,
    ins_dt = source.ins_dt,
    upd_dt = source.upd_dt,
    del_flag = source.del_flag,
    upd_dt = source.upd_dt
    WHEN NOT MATCHED THEN
INSERT
    (
        property_id,
        property_name,
        address_street,
        ruian_code,
        address_city,
        address_state,
        address_postal_code,
        address_district_code,
        address_latitude,
        address_longitude,
        property_type_id,
        property_subtype_id,
        property_number_of_floors,
        property_floor_number,
        property_location,
        property_construction_type,
        area_total_sqm,
        area_land_sqm,
        number_of_rooms,
        construction_year,
        last_reconstruction_year,
        energy_class_penb,
        property_condition,
        property_parking,
        property_heating,
        property_electricity,
        property_accessibility_id,
        property_balcony_sqm,
        property_terrace_sqm,
        property_garden_sqm,
        property_cellar_sqm,
        property_elevator,
        property_canalization,
        property_water_supply,
        property_air_conditioning,
        property_gas,
        property_internet,
        furnishing_level,
        ownership_type,
        is_active_listing,
        source_url,
        description,
        ins_dt,
        upd_dt,
        del_flag
    )
VALUES
    (
        source.property_id,
        source.property_name,
        source.address_street,
        source.ruian_code,
        source.address_city,
        source.address_state,
        source.address_postal_code,
        source.address_district_code,
        source.address_latitude,
        source.address_longitude,
        source.property_type_id,
        source.property_subtype_id,
        source.property_number_of_floors,
        source.property_floor_number,
        source.property_location,
        source.property_construction_type,
        source.area_total_sqm,
        source.area_land_sqm,
        source.number_of_rooms,
        source.construction_year,
        source.last_reconstruction_year,
        source.energy_class_penb,
        source.property_condition,
        source.property_parking,
        source.property_heating,
        source.property_electricity,
        source.property_accessibility_id,
        source.property_balcony_sqm,
        source.property_terrace_sqm,
        source.property_garden_sqm,
        source.property_cellar_sqm,
        source.property_elevator,
        source.property_canalization,
        source.property_water_supply,
        source.property_air_conditioning,
        source.property_gas,
        source.property_internet,
        source.furnishing_level,
        source.ownership_type,
        source.is_active_listing,
        source.source_url,
        source.description,
        source.ins_dt,
        source.upd_dt,
        source.del_flag
    );


source.property_id,
source.property_name,
source.address_street,
source.ruian_code,
source.address_city,
source.address_state,
source.address_postal_code,
source.address_district_code,
source.address_latitude,
source.address_longitude,
source.property_type_id,
source.property_subtype_id,
source.property_number_of_floors,
source.property_floor_number,
source.property_location,
source.property_construction_type,
source.area_total_sqm,
source.area_land_sqm,
source.number_of_rooms,
source.construction_year,
source.last_reconstruction_year,
source.energy_class_penb,
source.property_condition,
source.property_parking,
source.property_heating,
source.property_electricity,
source.property_accessibility_id,
source.property_balcony_sqm,
source.property_terrace_sqm,
source.property_garden_sqm,
source.property_cellar_sqm,
source.property_elevator,
source.property_canalization,
source.property_water_supply,
source.property_air_conditioning,
source.property_gas,
source.property_internet,
source.furnishing_level,
source.ownership_type,
source.is_active_listing,
source.source_url,
source.description,
source.ins_dt,
source.upd_dt,
source.del_flag,