# Hlavní konfigurace scraperu

# Výběr webů pro scraping (název = jméno třídy ve složce core/websites)
remax: true
sreality: false
bezrealitky: false
bidli: false
century21: false
idnes: false

# Filtry pro vyhledávání
filters:
  location:        # Lokalita (např. Praha, Brno, nebo prázdné pole pro všechny)
    # - Praha
    # - Brno
  property_type:   # Typ nemovitosti (např. Byt, Dům, Pozemek, nebo prázdné pole pro všechny)
    # - Byt
    # - Dům
  mode:            # Režim (prodej, pronajem)
    - Prodej
    # - Pronájem

# Výstupní formát a cílové úložiště
output:
  html: true         # Uložit HTML stránky
  csv: true          # Uložit data do CSV souboru
  json: true         # Uložit data do JSON souboru
  postgres: true     # Uložit data do PostgreSQL databáze

# Cesty k datům
paths:
  html: data/raw/html/
  raw: data/raw/
  cleaned: data/cleaned/
  images: data/images/
  

# Další nastavení
scraper:
  save_images: false     # Ukládat obrázky nemovitostí
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Scraper/1.0"
  parallel_websites: 2  # Kolik webů scrapovat paralelně
  parallel_details: 10  # Kolik detailů nemovitostí scrapovat paralelně

test_mode:
  enabled: true         # Pokud true, použije testovací limity
  max_pages: 2
  per_page: 3

# Logging configuration
logging: true
logging_level: 'INFO'  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
logging_file: 'logs/ebook_organizer.log'