# Hlavní konfigurace scraperu

# Výběr webů pro scraping (název = jméno třídy ve složce core/websites)
websites:
  - remax
  - sreality
  - bezrealitky


# Filtry pro vyhledávání
filters:
  location:        # Lokalita (např. Praha, Brno, nebo prázdné pole pro všechny)
    # - Praha
    # - Brno
  property_type:   # Typ nemovitosti (např. Byt, Dům, Pozemek, nebo prázdné pole pro všechny)
    # - Byt
    # - Dům
  mode: prodej     # Režim (prodej, pronajem)

# Výstupní formát a cílové úložiště
output:
  csv: true          # Uložit data do CSV souboru
  json: true         # Uložit data do JSON souboru
  postgres: true     # Uložit data do PostgreSQL databáze

# Cesty k datům
paths:
  html: data/raw/html/
  raw: data/raw/
  cleaned: data/cleaned/
  images: data/images/
  

# Další nastavení
scraper:
  max_pages: 10         # Maximální počet stránek ke stažení z každého webu (None = všechny)
  save_html: true       # Ukládat HTML stránky pro ladění
  save_images: true     # Ukládat obrázky nemovitostí
  user_agent: "Mozilla/5.0 (compatible; RealitkyScraper/1.0; +https://example.com/bot)"
  parallel_websites: 2  # Kolik webů scrapovat paralelně
  parallel_details: 10  # Kolik detailů nemovitostí scrapovat paralelně

test_mode:
  enabled: true         # Pokud true, použije testovací limity
  max_pages: 2
  per_page: 10

# Logování
logging:
  level: INFO           # Úroveň logování (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  file: logs/scraper.log