CREATE TABLE IF NOT EXISTS parsed.sreality (
    id text PRIMARY KEY,
    _embedded jsonb,
    _links jsonb,
    codeItems text,
    is_topped boolean,
    is_topped_today boolean,
    items jsonb,
    locality text,
    locality_district_id integer,
    logged_in boolean,
    map jsonb,
    meta_description text,
    name text,
    panorama jsonb,
    poi jsonb,
    poi_grocery jsonb,
    poi_leisure_time jsonb,
    poi_restaurant jsonb,
    poi_school_kindergarten jsonb,
    poi_transport jsonb,
    price_czk integer,
    recommendations_data jsonb,
    rus boolean,
    seo jsonb,
    text text