CREATE TABLE sreality (
    id BIGINT PRIMARY KEY,
    nazev TEXT,
    popis TEXT,
    kategorie_main INT,
    kategorie_sub INT,
    kategorie_type INT,
    lokalita TEXT,
    adresa TEXT,
    adresa_presnost TEXT,
    cena INT,
    cena_text TEXT,
    cena_puvodni INT,
    pozn_cena TEXT,
    stavba TEXT,
    stav_objektu TEXT,
    vlastnictvi TEXT,
    umisteni_objektu TEXT,
    podlazi TEXT,
    uzitna_plocha INT,
    sklep INT,
    garaz INT,
    datum_nastehovani TEXT,
    voda TEXT,
    odpad TEXT,
    telekomunikace TEXT,
    elektrina TEXT,
    doprava TEXT,
    komunikace TEXT,
    typ_bytu TEXT,
    lat NUMERIC,
    lon NUMERIC,
    kontakt_jmeno TEXT,
    kontakt_email TEXT,
    kontakt_telefon TEXT,
    obrazky JSONB
);